In [1]:
import pandas as pd

In [2]:
import xlsxwriter
import openpyxl
from openpyxl.styles import PatternFill
from openpyxl import Workbook
import openpyxl
from openpyxl.styles import Font

In [3]:
xls = pd.ExcelFile('otTraderPanel.xlsx')
df1 = pd.read_excel(xls, 'Sheet 1',header=[0,1])
df2 = pd.read_excel(xls, 'Sheet 2',header=[0,1])

In [4]:
df3 = pd.read_csv('OT_output4.csv')

In [5]:
df1

Empty DataFrame
Columns: [(Customer terms, Name), (Customer terms, Report), (Customer terms, Cargo), (Customer terms, Contractual qty(MT)), (Customer terms, Tolerance +/-(%)), (Customer terms, Quantity option), (Customer terms, Stow factor(cbft/mt)), (Customer terms, Load port), (Customer terms, Load rate(MT/day)), (Customer terms, Load terms), (Customer terms, Load draft(m)), (Customer terms, No. of berths), (Customer terms, Use cranes load), (Customer terms, Discharge port), (Customer terms, Discharge rate(MT/day)), (Customer terms, Discharge terms), (Customer terms, Discharge draft(m)), (Customer terms, No. of berths.1), (Customer terms, Use cranes disch), (Customer terms, Voyage sale addr comm(%)), (Customer terms, Voyage sale broker comm(%)), (Customer terms, Option part cargo), (Customer prices, 01-11-2022), (Customer prices, 01-12-2022), (Customer prices, 01-01-2023)]
Index: []

[0 rows x 25 columns]

In [6]:
df2

Empty DataFrame
Columns: [(Base cargo no parcel option terms, Base cargo name), (Base cargo no parcel option terms, Base cargo concatenated terms), (Base cargo no parcel option terms, Base cargo IMOS estimate), (Base cargo no parcel option prices, 01-11-2022), (Base cargo no parcel option prices, 01-12-2022), (Base cargo no parcel option prices, 01-01-2023), (Base cargo parcel option discounts/prices, 01-11-2022), (Base cargo parcel option discounts/prices, 01-12-2022), (Base cargo parcel option discounts/prices, 01-01-2023), (Top-off cargo economical stem no parcel option prices, Top-off cargo IMOS estimate), (Top-off cargo economical stem no parcel option prices, 01-11-2022), (Top-off cargo economical stem no parcel option prices, 01-12-2022), (Top-off cargo economical stem no parcel option prices, 01-01-2023), (Top-off cargo w/parcel option discounts, 01-11-2022), (Top-off cargo w/parcel option discounts, 01-12-2022), (Top-off cargo w/parcel option discounts, 01-01-2023), (Parcel calc terms, Parcel calc name), (Parcel calc terms, Parcel calc concatenated terms), (Parcel calc terms, Parcel calc IMOS estimate), (Parcel calc P&L, 01-11-2022), (Parcel calc P&L, 01-12-2022), (Parcel calc P&L, 01-01-2023), (Parcel calc INPUT P&L, 01-10-2022), (Parcel calc INPUT P&L, 01-11-2022), (Parcel calc INPUT P&L, 01-01-2023), (Parcel calc top-off parcel option PnL equivalent discount, 01-11-2022), (Parcel calc top-off parcel option PnL equivalent discount, 01-12-2022), (Parcel calc top-off parcel option PnL equivalent discount, 01-01-2023)]
Index: []

[0 rows x 28 columns]

In [7]:
df3

,Unnamed: 0,Parcel calc name,Parcel calc IMOS estimate,Parcel calc concatenated terms,Base cargo IMOS estimate,Top-off cargo IMOS estimate,Voyage sale addr comm(%),Top-off cargo concatenated terms,Base cargo concatenated terms,Voyage sale broker comm(%),...,Cargo,Load port,Use cranes disch,Discharge rate(MT/day),Discharge terms,Discharge draft(m),Discharge port,Stow factor(cbft/mt),Name,Report
0,0,45k iron NP Qingdao + 30k SBM Santos Kohsichang,RGE2-08498,41128 IRON ORE+15209 SOYABEANMEAL,RGE2-08649,RGE2-08470,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,20000,SHINC,NaN,KOHSICHANG TPP,53.0,SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP,SOYABEANMEAL//THAILAND
1,1,ironsoy1,RGE2-08502,41701 IRON ORE+19142 SOYABEANMEAL,RGE2-08649,RGE2-08470,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,20000,SHINC,NaN,KOHSICHANG TPP,53.0,SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP,SOYABEANMEAL//THAILAND
2,2,ironsoy2,RGE2-08469,49500 IRON ORE+23167 SOYABEANMEAL,RGE2-08649,RGE2-08470,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,20000,SHINC,NaN,KOHSICHANG TPP,53.0,SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP,SOYABEANMEAL//THAILAND
3,3,ironsoy3,RGE2-08504,49500 IRON ORE+31127 SOYABEANMEAL,RGE2-08649,RGE2-08470,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,20000,SHINC,NaN,KOHSICHANG TPP,53.0,SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP,SOYABEANMEAL//THAILAND
4,4,ironsoy4,RGE2-08516,43500 IRON ORE+60544 SOYABEANMEAL,RGE2-08649,RGE2-08470,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,20000,SHINC,NaN,KOHSICHANG TPP,53.0,SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP,SOYABEANMEAL//THAILAND
5,5,41 io + 15 maize,RGE2-08544,41206 IRON ORE+15208 MAIZE,RGE2-08649,RGE2-08543,3.75,72866 MAIZE SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,MAIZE,SANTOS,True,10000,SHINC,14.5,CAI MEP,46.0,MAIZE 46.0 SANTOS/ CAI MEP,MAIZE//VIETNAM
6,6,42 io + 17 maize,RGE2-08545,41813 IRON ORE+17000 MAIZE,RGE2-08649,RGE2-08543,3.75,72866 MAIZE SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,MAIZE,SANTOS,True,10000,SHINC,14.5,CAI MEP,46.0,MAIZE 46.0 SANTOS/ CAI MEP,MAIZE//VIETNAM
7,7,49.5 io + 23 maize,RGE2-08550,49500 IRON ORE+23241 MAIZE,RGE2-08649,RGE2-08543,3.75,72866 MAIZE SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,MAIZE,SANTOS,True,10000,SHINC,14.5,CAI MEP,46.0,MAIZE 46.0 SANTOS/ CAI MEP,MAIZE//VIETNAM
8,8,49.5 io + 30 maize,RGE2-08551,49500 IRON ORE+30000 SOYABEANMEAL,RGE2-08649,RGE2-08543,3.75,72866 MAIZE SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,MAIZE,SANTOS,True,10000,SHINC,14.5,CAI MEP,46.0,MAIZE 46.0 SANTOS/ CAI MEP,MAIZE//VIETNAM
9,9,41 io + 15 sbm,RGE2-08542,41206 IRON ORE+15208 SOYABEANMEAL,RGE2-08649,RGE2-08537,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,10000,SHINC,14.5,CAI MEP,53.0,SOYABEANMEAL 53.0 SANTOS/ CAI MEP,SOYABEANMEAL//VIETNAM
10,10,42 io + 17 sbm,RGE2-08541,41810 IRON ORE+19450 SOYABEANMEAL,RGE2-08649,RGE2-08537,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,10000,SHINC,14.5,CAI MEP,53.0,SOYABEANMEAL 53.0 SANTOS/ CAI MEP,SOYABEANMEAL//VIETNAM
11,11,49.5 io + 23 sbm,RGE2-08540,49500 IRON ORE+23241 SOYABEANMEAL,RGE2-08649,RGE2-08537,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,10000,SHINC,14.5,CAI MEP,53.0,SOYABEANMEAL 53.0 SANTOS/ CAI MEP,SOYABEANMEAL//VIETNAM
12,12,49.5 io + 27 sbm,RGE2-08539,49500 IRON ORE+27000 SOYABEANMEAL,RGE2-08649,RGE2-08537,3.75,64633 SOYABEANMEAL SANTOS,41286 IRON ORE NUEVA PALMIRA,0.0,...,SOYABEANMEAL,SANTOS,True,10000,SHINC,14.5,CAI MEP,53.0,SOYABEANMEAL 53.0 SANTOS/ CAI MEP,SOYABEANMEAL//VIETNAM

In [15]:
df1.loc.__setitem__((slice(None), ('Customer terms', 'Name')), df3['Name'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Report')), df3['Report'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Cargo')), df3['Cargo'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Contractual qty(MT)')), df3['comm'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Tolerance +/-(%)')), df3['comm'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Quantity option')), df3['comm'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Stow factor(cbft/mt)')), df3['Stow factor(cbft/mt)'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Load port')), df3['Load port'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Load rate(MT/day)')), df3['Load rate(MT/day)'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Load terms')), df3['Load terms'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Load draft(m)')), df3['Load draft(m)'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'No. of berths')), df3['comm'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Use cranes load')), df3['Use cranes load'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge port')), df3['Discharge port'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge rate(MT/day)')), df3['Discharge rate(MT/day)'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge terms')), df3['Discharge terms'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge draft(m)')), df3['Discharge draft(m)'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'No. of berths')), df3['comm'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Use cranes disch')), df3['Use cranes disch'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Voyage sale addr comm(%)')), df3['Voyage sale addr comm(%)'])
df1.loc.__setitem__((slice(None), ('Customer terms', 'Voyage sale broker comm(%)')), df3['Voyage sale broker comm(%)'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Option part cargo')), df3['comm'])

df1.loc.__setitem__((slice(None), ('Customer prices', '01-11-2022' )), df3['Customer price_01-12-2022'])
df1.loc.__setitem__((slice(None), ('Customer prices', '01-12-2022')), df3['Customer price_01-01-2023'])
df1.loc.__setitem__((slice(None), ('Customer prices', '01-01-2023')), df3['Customer price_01-02-2023'])

In [16]:
df1

                              Customer terms                          \
                                        Name                  Report
0   SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP  SOYABEANMEAL//THAILAND
1   SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP  SOYABEANMEAL//THAILAND
2   SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP  SOYABEANMEAL//THAILAND
3   SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP  SOYABEANMEAL//THAILAND
4   SOYABEANMEAL 53.0 SANTOS/ KOHSICHANG TPP  SOYABEANMEAL//THAILAND
5                 MAIZE 46.0 SANTOS/ CAI MEP          MAIZE//VIETNAM
6                 MAIZE 46.0 SANTOS/ CAI MEP          MAIZE//VIETNAM
7                 MAIZE 46.0 SANTOS/ CAI MEP          MAIZE//VIETNAM
8                 MAIZE 46.0 SANTOS/ CAI MEP          MAIZE//VIETNAM
9          SOYABEANMEAL 53.0 SANTOS/ CAI MEP   SOYABEANMEAL//VIETNAM
10         SOYABEANMEAL 53.0 SANTOS/ CAI MEP   SOYABEANMEAL//VIETNAM
11         SOYABEANMEAL 53.0 SANTOS/ CAI MEP   SOYABEANMEAL//VIETNAM
12         SOYABEANMEAL 53.0 SANTOS/ CAI MEP   SOYABEANMEAL//VIETNAM

                                                                       \
           Cargo Contractual qty(MT) Tolerance +/-(%) Quantity option
0   SOYABEANMEAL                 NaN              NaN             NaN
1   SOYABEANMEAL                 NaN              NaN             NaN
2   SOYABEANMEAL                 NaN              NaN             NaN
3   SOYABEANMEAL                 NaN              NaN             NaN
4   SOYABEANMEAL                 NaN              NaN             NaN
5          MAIZE                 NaN              NaN             NaN
6          MAIZE                 NaN              NaN             NaN
7          MAIZE                 NaN              NaN             NaN
8          MAIZE                 NaN              NaN             NaN
9   SOYABEANMEAL                 NaN              NaN             NaN
10  SOYABEANMEAL                 NaN              NaN             NaN
11  SOYABEANMEAL                 NaN              NaN             NaN
12  SOYABEANMEAL                 NaN              NaN             NaN

                                                                ...  \
   Stow factor(cbft/mt) Load port Load rate(MT/day) Load terms  ...
0                  53.0    SANTOS              8000      SHEX2  ...
1                  53.0    SANTOS              8000      SHEX2  ...
2                  53.0    SANTOS              8000      SHEX2  ...
3                  53.0    SANTOS              8000      SHEX2  ...
4                  53.0    SANTOS              8000      SHEX2  ...
5                  46.0    SANTOS              8000      SHEX2  ...
6                  46.0    SANTOS              8000      SHEX2  ...
7                  46.0    SANTOS              8000      SHEX2  ...
8                  46.0    SANTOS              8000      SHEX2  ...
9                  53.0    SANTOS              8000      SHEX2  ...
10                 53.0    SANTOS              8000      SHEX2  ...
11                 53.0    SANTOS              8000      SHEX2  ...
12                 53.0    SANTOS              8000      SHEX2  ...

                                                                        \
   Discharge terms Discharge draft(m) No. of berths.1 Use cranes disch
0            SHINC                NaN             NaN             True
1            SHINC                NaN             NaN             True
2            SHINC                NaN             NaN             True
3            SHINC                NaN             NaN             True
4            SHINC                NaN             NaN             True
5            SHINC               14.5             NaN             True
6            SHINC               14.5             NaN             True
7            SHINC               14.5             NaN             True
8            SHINC               14.5             NaN             True
9            SHINC               14.5             NaN             True
10           SHINC               14.5             NaN             True
11           SHINC               14.5             NaN             True
12           SHINC               14.5             NaN             True

                                                                          \
   Voyage sale addr comm(%) Voyage sale broker comm(%) Option part cargo
0                      3.75                        0.0               NaN
1                      3.75                        0.0               NaN
2                      3.75                        0.0               NaN
3                      3.75                        0.0               NaN
4                      3.75                        0.0               NaN
5                      3.75                        0.0               NaN
6                      3.75                        0.0               NaN
7                      3.75                        0.0               NaN
8                      3.75                        0.0               NaN
9                      3.75                        0.0               NaN
10                     3.75                        0.0               NaN
11                     3.75                        0.0               NaN
12                     3.75                        0.0               NaN

   Customer prices
        01-11-2022 01-12-2022 01-01-2023
0        42.600187  41.235179  38.540170
1        42.600187  41.235179  38.540170
2        42.600187  41.235179  38.540170
3        42.600187  41.235179  38.540170
4        42.600187  41.235179  38.540170
5        35.020046  32.371898  27.170195
6        35.020046  32.371898  27.170195
7        35.020046  32.371898  27.170195
8        35.020046  32.371898  27.170195
9        40.744167  37.798703  31.944430
10       40.744167  37.798703  31.944430
11       40.744167  37.798703  31.944430
12       40.744167  37.798703  31.944430

[13 rows x 25 columns]

In [21]:
df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo name')), df3['Base cargo name'])
df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['Base cargo concatenated terms'])
df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo IMOS estimate')), df3['Base cargo IMOS estimate'])

df2.loc.__setitem__((slice(None), ('Base cargo no parcel option prices', '01-12-2022')), df3['01-12-2022_base price'])
df2.loc.__setitem__((slice(None), ('Base cargo no parcel option prices', '01-01-2023')), df3['01-01-2023_base price'])
df2.loc.__setitem__((slice(None), ('Base cargo no parcel option prices', '01-02-2023')), df3['01-02-2023_base price'])

df2.loc.__setitem__((slice(None), ('Base cargo parcel option discounts/prices', '01-12-2022')), df3['01-12-2022_discount_base'])
df2.loc.__setitem__((slice(None), ('Base cargo parcel option discounts/prices', '01-01-2023')), df3['01-01-2023_discount_base'])
df2.loc.__setitem__((slice(None), ('Base cargo parcel option discounts/prices', '01-02-2023')), df3['01-02-2023_discount_base'])

df2.loc.__setitem__((slice(None), ('Top-off cargo economical stem no parcel option prices', 'Top-off cargo IMOS estimate')), df3['Top-off cargo IMOS estimate'])
df2.loc.__setitem__((slice(None), ('Top-off cargo economical stem no parcel option prices', '01-12-2022')), df3['01-12-2022_top off price'])
df2.loc.__setitem__((slice(None), ('Top-off cargo economical stem no parcel option prices', '01-01-2023')), df3['01-01-2023_top off price'])
df2.loc.__setitem__((slice(None), ('Top-off cargo economical stem no parcel option prices', '01-02-2023')), df3['01-02-2023_top off price'])

df2.loc.__setitem__((slice(None), ('Top-off cargo w/parcel option discounts', '01-12-2022')), df3['01-12-2022_discount_top off'])
df2.loc.__setitem__((slice(None), ('Top-off cargo w/parcel option discounts', '01-01-2023')), df3['01-01-2023_discount_top off'])
df2.loc.__setitem__((slice(None), ('Top-off cargo w/parcel option discounts', '01-02-2023')), df3['01-02-2023_discount_top off'])

df2.loc.__setitem__((slice(None), ('Parcel calc terms', 'Parcel calc name')), df3['Parcel calc name'])
df2.loc.__setitem__((slice(None), ('Parcel calc terms', 'Parcel calc concatenated terms')), df3['Parcel calc concatenated terms'])
df2.loc.__setitem__((slice(None), ('Parcel calc terms', 'Parcel calc IMOS estimate')), df3['Parcel calc IMOS estimate'])

df2.loc.__setitem__((slice(None), ('Parcel calc P&L', '01-12-2022')), df3['Parcel calc P&L_01-12-2022'])
df2.loc.__setitem__((slice(None), ('Parcel calc P&L', '01-01-2023')), df3['Parcel calc P&L_01-01-2023'])
df2.loc.__setitem__((slice(None), ('Parcel calc P&L', '01-02-2023')), df3['Parcel calc P&L_01-02-2023'])

# df2.loc.__setitem__((slice(None), ('Parcel calc INPUT P&L', '01-12-2022')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Parcel calc INPUT P&L', '01-01-2023')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Parcel calc INPUT P&L', '01-02-2023')), df3['Parcel calc P&L_01-02-2023'])

# df2.loc.__setitem__((slice(None), ('Parcel calc top-off parcel option PnL equivalent discount', '01-12-2022')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Parcel calc top-off parcel option PnL equivalent discount', '01-01-2023')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Parcel calc top-off parcel option PnL equivalent discount', '01-02-2023')), df3['comm'])

In [24]:
with pd.ExcelWriter('finalOTtrader.xlsx') as writer:  
    df1.to_excel(writer, sheet_name='Sheet 1')
    df2.to_excel(writer, sheet_name='Sheet 2')

In [ ]:
# df2
# baseCargoOptionTermMatch=[['Base cargo name'],
# [ 'Base cargo concatenated terms'],
# [ 'Base cargo IMOS estimate']]

In [11]:

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Name')), df3['comm'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Report')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Cargo')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Contractual qty(MT)')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Tolerance +/-(%)')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Quantity option')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Stow factor(cbft/mt)')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Load port')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Load rate(MT/day)')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Load terms')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Load draft(m)')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'No. of berths')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Use cranes load')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge port')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge rate(MT/day)')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge terms')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'Discharge draft(m)')), df3['comm'])

# df1.loc.__setitem__((slice(None), ('Customer terms', 'No. of berths')), df3['comm'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Use cranes disch')), df3['comm'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Voyage sale addr comm(%)')), df3['Voyage sale addr comm(%)'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Voyage sale broker comm(%)')), df3['Voyage sale broker comm(%)'])
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Option part cargo')), df3['comm'])

In [ ]:
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])
# df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', 'Base cargo concatenated terms')), df3['comm'])

In [32]:
# customTermMatch=[['Name'],
#                 ['Report'],
#                  ['Cargo'],
# #                  [''],
# #                  [''],
# #                  [''],
#                  ['Stow factor(cbft/mt)'],
#                  ['Load port'],
#                  ['Load rate(MT/day)'],
#                  ['Load terms'],
#                  ['Load draft(m)'],
# #                  [''],
#                  ['Use cranes load'],
#                  ['Discharge port'],
#                  ['Discharge rate(MT/day)'],
#                  ['Discharge terms'],
#                  ['Discharge draft(m)'],
# #                  [''],
#                  ['Use cranes disch'],
#                  ['Voyage sale addr comm(%)'],
#                  ['Voyage sale broker comm(%)']
# #                  ,
# #                  ['']
#                 ]
# df1['Voyage sale broker comm(%)']=df3['addr_comm']
# # df1['Option part cargo']=df3['']
# df1['01-11-2022']=df3['Customer price_11/01/2022']
# df1['01-12-2022']=df3['Customer price_12/01/2022']
# df1['01-01-2023']=df3['Customer price_01/01/2023']

In [40]:
# df1.loc.__setitem__((slice(None), ('Customer terms', 'Voyage sale addr comm(%)')), df3['Voyage sale addr comm(%)'])

InvalidIndexError: slice(None, None, None)

In [ ]:
# df1

In [35]:
# # for i in range(len(customTerms)):
#     df1.loc.__setitem__((slice(None), ('Customer terms', customTerms[i])), df3[customTermMatch[i]])

In [36]:
# customPriceDate=[['01-11-2022'], ['01-12-2022'], ['01-01-2023']]

In [37]:
# customPrice=[['Customer price_01-12-2022'],
# ['Customer price_01-01-2023'],
# ['Customer price_01-02-2023']]

In [31]:
# customTerms=[['Name'],
# [ 'Report'],
# [ 'Cargo'],
# # [ 'Contractual qty(MT)'],
# # [ 'Tolerance +/-(%)'],
# # [ 'Quantity option'],
# [ 'Stow factor(cbft/mt)'],
# [ 'Load port'],
# [ 'Load rate(MT/day)'],
# [ 'Load terms'],
# [ 'Load draft(m)'],
# # [ 'No. of berths'],
# [ 'Use cranes load'],
# [ 'Discharge port'],
# [ 'Discharge rate(MT/day)'],
# [ 'Discharge terms'],
# # [ 'Discharge draft(m)'],
# [ 'No. of berths'],
# [ 'Use cranes disch'],
# [ 'Voyage sale addr comm(%)'],
# [ 'Voyage sale broker comm(%)'],
# # [ 'Option part cargo']
#         ]

In [38]:
# for i in range(len(customPriceDate)):
#     df1.loc.__setitem__((slice(None), ('Customer prices', customPriceDate[i])), df3[customPrice[i]])
# #  df1.loc.__setitem__((slice(None), ('Customer prices', customPriceDate[i])), df3[customPrice[i]])

In [39]:
# df1

   Customer terms                                                    \
             Name Report Cargo Contractual qty(MT) Tolerance +/-(%)
0             NaN    NaN   NaN                 NaN              NaN
1             NaN    NaN   NaN                 NaN              NaN
2             NaN    NaN   NaN                 NaN              NaN
3             NaN    NaN   NaN                 NaN              NaN
4             NaN    NaN   NaN                 NaN              NaN
5             NaN    NaN   NaN                 NaN              NaN
6             NaN    NaN   NaN                 NaN              NaN
7             NaN    NaN   NaN                 NaN              NaN
8             NaN    NaN   NaN                 NaN              NaN
9             NaN    NaN   NaN                 NaN              NaN
10            NaN    NaN   NaN                 NaN              NaN
11            NaN    NaN   NaN                 NaN              NaN
12            NaN    NaN   NaN                 NaN              NaN

                                                                     \
   Quantity option Stow factor(cbft/mt) Load port Load rate(MT/day)
0              NaN                  NaN       NaN               NaN
1              NaN                  NaN       NaN               NaN
2              NaN                  NaN       NaN               NaN
3              NaN                  NaN       NaN               NaN
4              NaN                  NaN       NaN               NaN
5              NaN                  NaN       NaN               NaN
6              NaN                  NaN       NaN               NaN
7              NaN                  NaN       NaN               NaN
8              NaN                  NaN       NaN               NaN
9              NaN                  NaN       NaN               NaN
10             NaN                  NaN       NaN               NaN
11             NaN                  NaN       NaN               NaN
12             NaN                  NaN       NaN               NaN

               ...                                                     \
   Load terms  ... Discharge terms Discharge draft(m) No. of berths.1
0         NaN  ...             NaN                NaN             NaN
1         NaN  ...             NaN                NaN             NaN
2         NaN  ...             NaN                NaN             NaN
3         NaN  ...             NaN                NaN             NaN
4         NaN  ...             NaN                NaN             NaN
5         NaN  ...             NaN                NaN             NaN
6         NaN  ...             NaN                NaN             NaN
7         NaN  ...             NaN                NaN             NaN
8         NaN  ...             NaN                NaN             NaN
9         NaN  ...             NaN                NaN             NaN
10        NaN  ...             NaN                NaN             NaN
11        NaN  ...             NaN                NaN             NaN
12        NaN  ...             NaN                NaN             NaN

                                                                         \
   Use cranes disch Voyage sale addr comm(%) Voyage sale broker comm(%)
0               NaN                      NaN                        NaN
1               NaN                      NaN                        NaN
2               NaN                      NaN                        NaN
3               NaN                      NaN                        NaN
4               NaN                      NaN                        NaN
5               NaN                      NaN                        NaN
6               NaN                      NaN                        NaN
7               NaN                      NaN                        NaN
8               NaN                      NaN                        NaN
9               NaN                      NaN                        NaN
10              NaN                      NaN                        NaN
11              NaN                      NaN                        NaN
12              NaN                      NaN                        NaN

                     Customer prices
   Option part cargo      01-11-2022 01-12-2022 01-01-2023
0                NaN             NaN        NaN        NaN
1                NaN             NaN        NaN        NaN
2                NaN             NaN        NaN        NaN
3                NaN             NaN        NaN        NaN
4                NaN             NaN        NaN        NaN
5                NaN             NaN        NaN        NaN
6                NaN             NaN        NaN        NaN
7                NaN             NaN        NaN        NaN
8                NaN             NaN        NaN        NaN
9                NaN             NaN        NaN        NaN
10               NaN             NaN        NaN        NaN
11               NaN             NaN        NaN        NaN
12               NaN             NaN        NaN        NaN

[13 rows x 25 columns]

In [15]:
# df3

In [19]:
# df2

Empty DataFrame
Columns: [(Base cargo no parcel option terms, Base cargo name), (Base cargo no parcel option terms, Base cargo concatenated terms), (Base cargo no parcel option terms, Base cargo IMOS estimate), (Base cargo no parcel option prices, 01-11-2022), (Base cargo no parcel option prices, 01-12-2022), (Base cargo no parcel option prices, 01-01-2023), (Base cargo parcel option discounts/prices, 01-11-2022), (Base cargo parcel option discounts/prices, 01-12-2022), (Base cargo parcel option discounts/prices, 01-01-2023), (Top-off cargo economical stem no parcel option prices, Top-off cargo IMOS estimate), (Top-off cargo economical stem no parcel option prices, 01-11-2022), (Top-off cargo economical stem no parcel option prices, 01-12-2022), (Top-off cargo economical stem no parcel option prices, 01-01-2023), (Top-off cargo w/parcel option discounts, 01-11-2022), (Top-off cargo w/parcel option discounts, 01-12-2022), (Top-off cargo w/parcel option discounts, 01-01-2023), (Parcel calc terms, Parcel calc name), (Parcel calc terms, Parcel calc concatenated terms), (Parcel calc terms, Parcel calc IMOS estimate), (Parcel calc P&L, 01-11-2022), (Parcel calc P&L, 01-12-2022), (Parcel calc P&L, 01-01-2023), (Parcel calc INPUT P&L, 01-10-2022), (Parcel calc INPUT P&L, 01-11-2022), (Parcel calc INPUT P&L, 01-01-2023), (Parcel calc top-off parcel option PnL equivalent discount, 01-11-2022), (Parcel calc top-off parcel option PnL equivalent discount, 01-12-2022), (Parcel calc top-off parcel option PnL equivalent discount, 01-01-2023)]
Index: []

[0 rows x 28 columns]

In [19]:
# baseCargoOptionTerm=[['Base cargo name'],
# [ 'Base cargo concatenated terms'],
# [ 'Base cargo IMOS estimate']]

In [20]:
# baseCargoOptionTermMatch=[['Base cargo name'],
# [ 'Base cargo concatenated terms'],
# [ 'Base cargo IMOS estimate']]

In [25]:
# for i in range(len(baseCargoOptionTerm)):
#     df2.loc.__setitem__((slice(None), ('Base cargo no parcel option terms', baseCargoOptionTerm[i])), df3[baseCargoOptionTermMatch[i]])

In [26]:
# df2

Empty DataFrame
Columns: [(Base cargo no parcel option terms, Base cargo name), (Base cargo no parcel option terms, Base cargo concatenated terms), (Base cargo no parcel option terms, Base cargo IMOS estimate), (Base cargo no parcel option prices, 01-11-2022), (Base cargo no parcel option prices, 01-12-2022), (Base cargo no parcel option prices, 01-01-2023), (Base cargo parcel option discounts/prices, 01-11-2022), (Base cargo parcel option discounts/prices, 01-12-2022), (Base cargo parcel option discounts/prices, 01-01-2023), (Top-off cargo economical stem no parcel option prices, Top-off cargo IMOS estimate), (Top-off cargo economical stem no parcel option prices, 01-11-2022), (Top-off cargo economical stem no parcel option prices, 01-12-2022), (Top-off cargo economical stem no parcel option prices, 01-01-2023), (Top-off cargo w/parcel option discounts, 01-11-2022), (Top-off cargo w/parcel option discounts, 01-12-2022), (Top-off cargo w/parcel option discounts, 01-01-2023), (Parcel calc terms, Parcel calc name), (Parcel calc terms, Parcel calc concatenated terms), (Parcel calc terms, Parcel calc IMOS estimate), (Parcel calc P&L, 01-11-2022), (Parcel calc P&L, 01-12-2022), (Parcel calc P&L, 01-01-2023), (Parcel calc INPUT P&L, 01-10-2022), (Parcel calc INPUT P&L, 01-11-2022), (Parcel calc INPUT P&L, 01-01-2023), (Parcel calc top-off parcel option PnL equivalent discount, 01-11-2022), (Parcel calc top-off parcel option PnL equivalent discount, 01-12-2022), (Parcel calc top-off parcel option PnL equivalent discount, 01-01-2023)]
Index: []

[0 rows x 28 columns]

In [30]:
# baseCargoOptionPrice=[['01-12-2022'],
# ['01-01-2023'],
# ['01-02-2023']]

In [31]:
# baseCargoOptionPriceMatch=[['01-12-2022_discount_base'],
# [ '01/01/2023_base price'],
# [ '01-02-2023_discount_base']]

In [32]:
# for i in range(len(baseCargoOptionPrice)):
#     df2.loc.__setitem__((slice(None), ('Base cargo no parcel option prices', baseCargoOptionPrice[i])), df3[baseCargoOptionPriceMatch[i]])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [27]:
# baseCargoDiscPrice=[['01-12-2022'],
# ['01-01-2023'],
# ['01-02-2023']]

In [28]:
# baseCargoDiscPriceMatch=[['01-12-2022_discount_base'],
# [ '01-01-2023_discount_base'],
# [ '01-02-2023_discount_base']]

In [29]:
# for i in range(len(customPrice)):
#     df2.loc.__setitem__((slice(None), ('Base cargo parcel option discounts/prices', baseCargoDiscPrice[i])), df3[baseCargoDiscPriceMatch[i]])

C:\Users\nalin.jindal\AppData\Local\Temp\ipykernel_13620\3517914017.py:2: FutureWarning: The behavior of indexing on a MultiIndex with a nested sequence of labels is deprecated and will change in a future version. `series.loc[label, sequence]` will raise if any members of 'sequence' or not present in the index's second level. To retain the old behavior, use `series.index.isin(sequence, level=1)`
  df2.loc.__setitem__((slice(None), ('Base cargo parcel option discounts/prices', baseCargoDiscPrice[i])), df3[baseCargoDiscPriceMatch[i]])

In [36]:
# topOfcargpoPrice=[['Top-off cargo IMOS estimate'],
# ['01-12-2022'],
# ['01-01-2023'],
# ['01-02-2023']]

In [37]:
# topOfcargpoPriceMatch=[['Top-off cargo IMOS estimate'],
# [ ''],
# [ ''],
#  ['']]

In [38]:
# for i in range(len(customPrice)):
#     df2.loc.__setitem__((slice(None), ('Top-off cargo economical stem no parcel option prices', topOfcargpoPrice[i])), df3[topOfcargpoPriceMatch[i]])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [14]:
# topOfCargoDiscount=[['01-12-2022'],
# ['01-01-2023'],
# ['01-02-2023']]

In [15]:
# topOfCargoDiscountMatch=[['12/01/2022_discount_top off'],
# [ '01/01/2023_discount_top off'],
# [ '']]

In [17]:
# for i in range(len(topOfCargoDiscount)):
#     df2.loc.__setitem__((slice(None), ('Top-off cargo w/parcel option discounts', topOfCargoDiscount[i])), df3[topOfCargoDiscountMatch[i]])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [42]:
# parcelCalcTerm=[['Parcel calc name'],
# ['Parcel calc concatenated terms'],
# ['Parcel calc IMOS estimate']
# ]

In [43]:
# parcelCalcTermMatch=[[''],
# [ ''],
# [ '']]

In [ ]:
#                     prices[ '01-11-2022'], ['01-12-2022'], ['01-01-2023']
# 
# ['Name'],
# [ 'Report'],
# [ 'Cargo'],
# # [ 'Contractual qty(MT)'],
# # [ 'Tolerance +/-(%)'],
# # [ 'Quantity option'],
# [ 'Stow factor(cbft/mt)'],
# [ 'Load port'],
# [ 'Load rate(MT/day)'],
# [ 'Load terms'],
# [ 'Load draft(m)'],
# # [ 'No. of berths'],
# [ 'Use cranes load'],
# [ 'Discharge port'],
# [ 'Discharge rate(MT/day)'],
# [ 'Discharge terms'],
# # [ 'Discharge draft(m)'],
# [ 'No. of berths'],
# [ 'Use cranes disch'],
# [ 'Voyage sale addr comm(%)'],
# [ 'Voyage sale broker comm(%)'],
# # [ 'Option part cargo']

In [44]:
# for i in range(len(parcelCalcTerm)):
#     df2.loc.__setitem__((slice(None), ('Parcel calc terms', parcelCalcTerm[i])), df3[parcelCalcTermMatch[i]])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [45]:
# parcelCalcpnl=[['01-12-2022'],
# ['01-01-2023'],
# ['01-02-2023']]

In [46]:
# parcelCalcpnlMatch=[[''],
# [ ''],
# [ '']]

In [47]:
# for i in range(len(parcelCalcpnl)):
#     df2.loc.__setitem__((slice(None), ('Parcel calc P&L', parcelCalcpnl[i])), df3[parcelCalcpnlMatch[i]])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [48]:
# parcelCalcInputPnl=[['01-12-2022'],
# ['01-01-2023'],
# ['01-02-2023']]

In [49]:
# parcelCalcInputPnlMatch=[[''],
# [ ''],
# [ '']]

In [50]:
# for i in range(len(parcelCalcInputPnl)):
#     df2.loc.__setitem__((slice(None), ('Parcel calc INPUT P&L', parcelCalcInputPnl[i])), df3[parcelCalcInputPnlMatch[i]])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [51]:
# parcelCalctopOffPnl=[['01-12-2022'],
# ['01-01-2023'],
# ['01-02-2023']]

In [52]:
# parcelCalctopOffPnlMatch=[[''],
# [ ''],
# [ '']]

In [53]:
# for i in range(len(parcelCalctopOffPnl)):
#     df2.loc.__setitem__((slice(None), ('Parcel calc top-off parcel option PnL equivalent discount', parcelCalctopOffPnl[i])), df3[parcelCalctopOffPnlMatch[i]])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [21]:
# import pandas as pd
# # import pyxlsb

In [22]:
# xls = pd.ExcelFile('otTraderPanel.xlsx')
# df1 = pd.read_excel(xls, 'Sheet 1',header=[0,1])
# df2 = pd.read_excel(xls, 'Sheet 2',header=[0,1])

In [24]:
# existingdf.to_excel(r'PATH\filename.xlsb')

In [25]:
# with pd.ExcelWriter('filename.xlsb',) as writer:  
#     df1.to_excel(writer, sheet_name='Sheet 1')
#     df2.to_excel(writer, sheet_name='Sheet 2')

ValueError: No engine for filetype: 'xlsb'

In [ ]:
# df1.loc.__setitem__((slice(None), ('Customer prices', '01-11-2022')), df3['Customer price_11/01/2022'])
# df1.loc.__setitem__((slice(None), ('Customer prices', '01-12-2022')), df3['Customer price_12/01/2022'])
# df1.loc.__setitem__((slice(None), ('Customer prices', '01-01-2023')), df3['Customer price_01/01/2023'])

In [ ]:
# df1

In [ ]:
# df2.columns = [df2.iloc[0]]
# df2 = df2[1:]
# # df.head()

In [ ]:
# df2

In [ ]:
# df1['Name']=df3['']
# df1['Report']=df3['']
# df1['Cargo']=df3['Base cargo']
# df1['Contractual qty(MT)']=df3['']
# df1['Tolerance +/-(%)']=df3['']
# df1['Quantity option']=df3['']
# df1['Stow factor(cbft/mt)']=df3['']
# df1['Load port']=df3['']
# df1['Load rate(MT/day)']=df3['']
# df1['Load terms']=df3['']
# df1['Load draft(m)']=df3['']
# df1['No. of berths']=df3['']
# df1['Use cranes load']=df3['']
# df1['Discharge port']=df3['']
# df1['Discharge rate(MT/day)']=df3['']
# df1['Discharge terms']=df3['']
# df1['Discharge draft(m)']=df3['']
# df1['No. of berths']=df3['']
# df1['Use cranes disch']=df3['']
# df1.xs('Customer terms',level='S',axis=1)
# df1['Voyage sale addr comm(%)']= df3['comm']
# df1['Customer terms']['Voyage sale addr comm(%)']= df3['comm']
# df1.__getitem__('Customer terms').__setitem__('Voyage sale addr comm(%)', df3['comm'])

In [8]:
# df1.columns = [df1.iloc[0],df1.iloc[1]]
# df1 = df1[1:]

In [16]:
# df2['Base cargo name']=df3['Base cargo']
# df2['Base cargo concatenated terms']=df3['']


# df2['Base cargo IMOS estimate']=df3['Base cargo IMOS estimate']
# df2['01-11-2022']=df3['11/01/2022_base price']
# df2['01-12-2022']=df3['12/01/2022_base price']
# df2['01-01-2023']=df3['01/01/2023_base price']
# df2['01-11-2022']=df3['11/01/2022_disc_base']
# df2['01-12-2022']=df3['12/01/2022_disc_base']
# df2['01-01-2023']=df3['01/01/2023_disc_base']
# df2['Top-off cargo IMOS estimate']=df3['Top-off cargo IMOS estimate']
# df2['01-11-2022']=df3['11/01/2022_top off price']
# df2['01-12-2022']=df3['12/01/2022_top off price']
# df2['01-01-2023']=df3['01/01/2023_top off price']
# df2['01-11-2022']=df3['11/01/2022_disc_top off']
# df2['01-12-2022']=df3['12/01/2022_disc_top off']
# df2['01-01-2023']=df3['01/01/2023_disc_top off']
# df2['Parcel calc name']=df3['Parcel calc name']
# # df2['Parcel calc concatenated terms']=df3['']
# df2['Parcel calc IMOS estimate']=df3['Parcel calc IMOS estimate']
# # df2['01-11-2022']=df3['']
# # df2['01-12-2022']=df3['']
# # df2['01-01-2023']=df3['']
# # df2['01-10-2022']=df3['']
# # df2['01-11-2022']=df3['']
# # df2['01-01-2023']=df3['']
# # df2['01-11-2022']=df3['']
# # df2['01-12-2022']=df3['']
# # df2['01-01-2023']=df3['']

In [17]:
# df1.columns = df1.iloc[1]
# df1 = df1[0:]

In [18]:
# df2.columns = df2.iloc[1]
# df2 = df2[0:]

In [19]:
# df1

In [18]:
# df2

In [21]:
# with pd.ExcelWriter('finalOTtrader.xlsx') as writer:  
#     df1.to_excel(writer, sheet_name='Sheet 1')
#     df2.to_excel(writer, sheet_name='Sheet 2')